Update checkpoint.py for quantization_bit setting
MaximIntegratedAI/ai8x-synthesis pull request #285
Opened 2023-03-06 12:31 UTC by seldauyanik-maxim

Checkpoint.py was determining quantization_bits per layer automatically using layer weights' interval resulting in a faulty value for some samples. This sections are updated to use weight_bits instead.

2023-03-07 22:05 UTC, ermanok submitted a review, later dismissed
Looks good.

2023-03-20 21:41 UTC, rotx-maxim requested changes
Please merge https://github.com/seldauyanik-maxim/ai8x-synthesis/pull/1

2023-03-21 20:20 UTC, rotx-maxim approved these changes

2023-03-21 20:58 UTC, rotx-maxim approved these changes

2023-03-21 21:18 UTC, merged