Bayer2RGB model added to synthesis repository.
MaximIntegratedAI/ai8x-synthesis pull request #304
Opened 2023-09-12 12:17 UTC by asyatrhl

2023-09-13 13:27 UTC, rotx-maxim requested changes

2023-09-13 13:27 UTC, rotx-maxim commented on networks/ai85_bayer2rgb.yaml
Rename to ai85-bayer2rgb.yaml (and update scripts) for consistency

2023-09-15 13:57 UTC, rotx-maxim approved these changes

2023-09-18 05:15 UTC, ermanok approved these changes
That's good.

2023-09-18 13:12 UTC, merged